# ASR Hub 配置檔案

# 系統配置
system:
  name: "ASR Hub"
  version: "0.1.0"
  mode: "development"  # development | production
  debug: true

# API 配置
api:
  # HTTP SSE 配置（總是啟用）
  http_sse:
    host: "0.0.0.0"
    port: 8000
    cors_enabled: true
    cors_origins: ["*"]
    max_connections: 100
    request_timeout: 300  # 秒
    
  # WebSocket 配置
  websocket:
    enabled: false
    port: 8001
    
  # gRPC 配置
  grpc:
    enabled: false
    port: 50051
    
  # Socket.IO 配置
  socketio:
    enabled: false
    port: 8002
    
  # Redis 配置
  redis:
    enabled: false
    host: "localhost"
    port: 6379

# Pipeline 配置
pipeline:
  # 預設音訊參數
  sample_rate: 16000
  channels: 1
  encoding: "linear16"
  
  # 緩衝區設定
  buffer_size: 8192
  
  # Operators 配置
  operators:
    # 取樣率調整
    sample_rate_adjustment:
      enabled: true
      target_rate: 16000
      quality: "high"  # low | medium | high
      
    # VAD (Voice Activity Detection)
    vad:
      enabled: false
      sensitivity: 0.5
      
    # 降噪
    denoise:
      enabled: false
      level: "medium"  # low | medium | high

# Provider 配置
providers:
  default: "whisper"
  
  # Whisper 配置
  whisper:
    enabled: true
    model_size: "base"  # tiny | base | small | medium | large
    language: "auto"    # auto | zh | en | ...
    device: "cpu"       # cpu | cuda | mps
    compute_type: "default"  # default | float32 | float16 | int8
    use_faster_whisper: true
    model_path: "./models"
    
    # Whisper 特定參數
    beam_size: 5
    best_of: 5
    temperature: 0.0
    initial_prompt: null
    vad_filter: true
    
    # 串流處理參數
    chunk_length: 30      # 秒
    overlap_length: 5     # 秒
    
  # FunASR 配置
  funasr:
    enabled: false
    model_name: "paraformer"
    
  # Vosk 配置
  vosk:
    enabled: false
    model_path: "./models/vosk"
    
  # Azure 配置
  azure:
    enabled: false
    subscription_key: ""
    region: "eastasia"

# 串流配置
stream:
  buffer_size: 8192
  silence_timeout: 3.0      # 秒
  max_segment_duration: 30.0  # 秒
  enable_vad: false

# 喚醒詞配置
wakeword:
  enabled: false
  keywords: ["小助手", "Hey Assistant"]
  sensitivity: 0.5

# 效能配置
performance:
  # 執行緒池配置
  thread_pool:
    max_workers: 4
    
  # 記憶體限制
  memory:
    max_buffer_size: 104857600  # 100MB
    
  # GPU 配置
  gpu:
    enabled: false
    device_id: 0
    memory_fraction: 0.8

# 日誌配置
logging:
  level: "INFO"  # DEBUG | INFO | WARNING | ERROR
  format: "pretty"  # pretty | json | simple | standard
  path: "./logs"  # 日誌文件路徑
  rotation: "daily"  # daily | size | time | 100 MB | 1 week
  retention: 7  # 天
  console:
    enabled: true
    colorize: true
  file:
    enabled: true

# 監控配置
monitoring:
  enabled: false
  metrics:
    enabled: false
    port: 9090
  health_check:
    enabled: true
    endpoint: "/health"