# ASR Hub 池化配置範例
# 展示如何在 Provider 中啟用池化功能

# ===== ASR Provider 設定 =====
providers:
  default: "whisper"  # 預設使用的 provider
  
  # Local Whisper with Pool
  whisper:
    enabled: true
    model_size: ${WHISPER_MODEL:base}
    language: "zh"
    device: ${WHISPER_DEVICE:cpu}
    compute_type: "float32"
    beam_size: 5
    best_of: 5
    temperature: 0.0
    model_path: "./models/whisper"
    
    # 池化配置
    pool:
      enabled: true  # 啟用池化
      min_size: 2    # 最小池大小
      max_size: 10   # 最大池大小
      acquire_timeout: 30.0  # 獲取實例的超時時間（秒）
      idle_timeout: 300.0    # 空閒實例的超時時間（秒）
      health_check_interval: 60.0  # 健康檢查間隔（秒）
  
  # FunASR without Pool (單例模式)
  funasr:
    enabled: false
    model: "paraformer"
    language: "zh"
    device: "cpu"
    model_path: "./models/funasr"
    # 沒有 pool 配置，使用單例模式
    
  # Vosk with Pool
  vosk:
    enabled: false
    model_path: "./models/vosk/vosk-model-cn-0.22"
    sample_rate: 16000
    
    # 池化配置
    pool:
      enabled: true
      min_size: 1
      max_size: 5
      acquire_timeout: 20.0
      idle_timeout: 180.0
      health_check_interval: 30.0

# ===== 效能設定 =====
performance:
  # 執行緒池設定
  thread_pool:
    min_workers: 4   # 增加最小工作執行緒以配合池化
    max_workers: 20  # 增加最大工作執行緒
    
  # 記憶體限制
  memory:
    max_usage_mb: 4096  # 增加記憶體限制以支持多個實例
    gc_threshold: 0.8